### ISSUE TITLE
this example does not work?

### ISSUE THREAD

**Issue by barthuijgen** [MetaMask/ledger-hardware-wallet-snap#2]
Trying to implement this results in `navigator` being undefined. trying to add the `"endowment:webhid": {}` snap permission results in an error when installing the snap that the permission does not exist.

it is also not listed on: https://docs.metamask.io/snaps/reference/permissions/

how is this supposed to work?

**Comment by gantunesr** [comment]
hi @barthuijgen, this project is outdated and we're not maintaining it. The repository will soon be updated to reflect the state of the project
